version: "2"
services:
    wordpress:
        image: wordpress:latest
        ports:
            - "8080:80"
        depends_on:
            - db
        environment:
            WORDPRESS_DB_HOST: "db:3306"
        env_file: .env
        volumes:
            - ./.dist/main:/var/www/html/wp-content/themes/boilerplate
    db:
        image: mysql:latest
        env_file: .env
        volumes:
            - db-data:/var/lib/mysql
volumes:
    db-data:
        driver: local
